# Generated by Django 4.2.5 on 2024-07-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
