# Generated by Django 4.2.5 on 2023-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'man'), (2, 'woman')], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='12'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
